#!/bin/sh
    echo $(date)
    echo "Git PEN: I am working on ./$1"
    author=$(git config --get user.name)
    email=$(git config --get user.email)
    timestamp=$(date +%s)
    plaintext=$1
    hash=$(git hash-object $1)
    head=$(git log -1 HEAD --pretty=format:"%H")
    master=$(git log -1 master --pretty=format:"%H")
    home=$(git rev-parse --abbrev-ref HEAD)
    echo "Stashing working directory"
    git stash
    git checkout notify
    git pull origin notify
    echo "{\"author\":\""$author"\", \"email\":\""$email"\", \"time\":\""$timestamp"\", \"file\":\""./$plaintext"\", \"file\":\""$hash"\", \"lastMaster\":\""$master"\", \"lastCommit\":\""$head"\"}" >> log.md
    git add .
    git commit -m "Test upload"
    git push origin notify
    git checkout $home
    echo "Reverting to working directory"
    git stash apply