#!/bin/sh
    home=$(git rev-parse --abbrev-ref HEAD)
    echo $(date)
    echo "Stashing working directory"
    git stash
    git checkout notify
    git pull origin notify
    touch $RANDOM.txt
    git add .
    git commit -m "Test upload"
    git push origin notify
    git checkout $home
    echo "Reverting to working directory"
    git stash apply