#!/bin/sh
    echo $(date)
    echo "Git PEN: I am working on ./$1"
    author=$(git config --get user.name)
    email=$(git config --get user.email)
    hash=$(git hash-object $1)
    head=$(git log -1 HEAD --pretty=format:"%H")
    home=$(git rev-parse --abbrev-ref HEAD)
    master=$(git log -1 master --pretty=format:"%H")
    message=${2:-""}
    plaintext=$1
    timestamp=$(date +%s)
    echo "Stashing working directory"
    git stash
    git checkout notify
    echo !log.md
    git pull origin notify
    git add .
    git commit -m "$author cleaning notify directory"
    git push origin notify
    git checkout $home
    echo "Reverting to working directory"
    git stash pop
    echo "Notifying server"
    wget -qO- http://penjs.herokuapp.com/notify &> /dev/null