#!/bin/sh
    echo $(date)
    echo "Git PEN: I am working on ./$1"
    author=$(git config --get user.name)
    email=$(git config --get user.email)
    hash=$(git hash-object $1)
    head=$(git log -1 HEAD --pretty=format:"%H")
    home=$(git rev-parse --abbrev-ref HEAD)
    master=$(git log -1 master --pretty=format:"%H")
    message=${2:-""}
    plaintext=$1
    timestamp=$(date +%s)
    
    if [ -z "$author" ];
        then
        echo "You need to set up your authorname in order to use this properly"
        echo 'You need to type git config user.name "Firstname Lastname"'
        exit 1
    elif [ -z "$hash" ];
        then
        echo "You are trying to pen a file that does not exist or is not tracked in git, please check and restart"
        exit 1
        
    elif [ $3="-v" ];
        then
        echo "Stashing working directory"
        git stash
        git checkout notify
        git pull origin notify
        echo "{\"author\":\""$author"\", \"email\":\""$email"\", \"time\":\""$timestamp"\", \"file\":\""./$plaintext"\", \"message\":\""$message"\", \"SHA\":\""$hash"\", \"lastMaster\":\""$master"\", \"lastCommit\":\""$head"\"}" >> log.md
        git add .
        git commit -m "$author working on ./$1"
        git push origin notify
        git checkout $home
        echo "Reverting to working directory"
        git stash pop
        echo "Notifying server"
        wget -qO- http://penjs.herokuapp.com/notify &> /dev/null
        exit 0
    else

        echo "Stashing working directory"
        git stash -q
        git checkout -q notify
        git pull -q origin notify
        echo "{\"author\":\""$author"\", \"email\":\""$email"\", \"time\":\""$timestamp"\", \"file\":\""./$plaintext"\", \"message\":\""$message"\", \"SHA\":\""$hash"\", \"lastMaster\":\""$master"\", \"lastCommit\":\""$head"\"}" >> log.md
        git add .
        git commit --quiet -m "$author working on ./$1"
        git push -q origin notify
        git checkout -q $home
        echo "Reverting to working directory"
        git stash -q pop
        echo "Notifying server"
        wget -qO- http://penjs.herokuapp.com/notify &> /dev/null
    fi